# patch_nfs_details.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: NFS_SERVER
              value: ${ NFS_IP }
            - name: NFS_PATH
              value: /srv/nfs4/k3s
      volumes:
        - name: nfs-client-root
          nfs:
            server: ${ NFS_IP }
            path: /srv/nfs4/k3s
