# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:RCnHdKc2DYOsn2mGR0kqyWVb,iv:pHsRCXaIZ/BEWYKrl53URK5eoYPGbNDguFMiEHcQ050=,tag:LNU35eA0pXuMBMorQmXBww==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:kFIChoEISSJaUxHJrd8iRFUH4OZ6HOQv6sNITKbO7ovtE4a7BQ==,iv:TS/epX1qL81gdB/VIOlIaGHdHRIN4DUh307J+ow3RqM=,tag:p1kmfPDtWdl6b3uqy4xCTw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:NA2tu9CDc5GO/fCSrwyuAiQLRRs=,iv:mMxVVJuDCsoUn/mi4KOMLEES+VtTZj4fgnWiN3/kec4=,tag:xUsSNFZt5qSZtzRRSzS8pw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e7eh6y2mka5euucx9xqdt70l3mcdp7dcfq5s2v7d8ahr29ww042sqfnvrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3V3RjODFpdWhQaWU2N1gy
            Q05WRGFQOGQ1MWN5RFkzOGpybnN4c1QwdVJrCkhSMDB3RHJvTHluWlFBNHIxODhI
            ZGtFY2ZDcXd3QUJBeG5ERDdNTU5uenMKLS0tIEdBS2pnWGcvRWFJc3o5Q2VkMUR0
            d3RxaGNiTHlySVE1akgvOS9ldXBibHMKcZUyiguqP4LQDmEfHvBGc71+9cORnTEs
            Pd28Hl3jW0FN3bmpt8ilv8SPJbk251+1SJA3WaRCGnpTDaiYN5c1yA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-29T07:53:22Z"
    mac: ENC[AES256_GCM,data:OhyOU5T/Zxv67n2XHakI5Oj3itNe2hINWb+3iVXh8/POkhj/BvBllyfNjdg3m9+r8tFI3wgo5xUnJXVbDfxXvLuBXoHKQ3ftgPzNr/qSkAC4cgPishtPUZD57aYFUxDxCdNNagICTbCBy7XQRMGa6/P3PfM8d7z6XtbjQUbC/z4=,iv:MEIZWvacxUDjbF4As2SA8AeVfL1feeXL692Aoekuh6w=,tag:Nw05lXsVsEpZ71Q0SZWgcw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
