# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:tXNOdqxOFRli63JmCHqY0W/U,iv:DNLdmJ03zLDapCbr8zpg/ekFCWF7uaKZd/AWDctuf6A=,tag:o5xpwupYPNTFYo/IxVYinw==,type:str]
    api-key: ENC[AES256_GCM,data:zEgiuQqhRw9EvDM5USPWqPTurwg6CdnsoV1fo8zO9gOiG64TmA==,iv:NY4UrnP/oFW76VDyv/4H2LdmgAUon73X74/4O/yHU68=,tag:CY9cT230IIaiTSbCFpjtbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e7eh6y2mka5euucx9xqdt70l3mcdp7dcfq5s2v7d8ahr29ww042sqfnvrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwd3lSY0hTSmZ1bTNiY2Yv
            Y0pXWnpQeGQwc2p3TURVa0RPL2ZoeXhKVG1nCm5EMkVhOWdGSWZyc0pWTXZ3Nmps
            MGJTU3JPQXJGcDVOKzFMVUhPcmQxcUEKLS0tIFVSZnFZNjNyTzZHZ3ZYeE1rZFFK
            WUpIUWdNOGpKQ0JTMFJlcysrSWFTZjQK3pHbq1fPsFH3qRdr8pEUwiz277Sd75iR
            klyQmWT1rHmRcvKPtBB+u9B3hAtxvF2GWo4NMN/llcXJk/hOnnJeIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-29T07:53:22Z"
    mac: ENC[AES256_GCM,data:z1+G8hEITDStAQFdhlNVTRNChHqzHUejHyOOg3rx85CfKAB127ANQIcfFpliwFUWEoO7OHqI5J4PRdqUdvhMPUZxjZtJX+pTgwooV8ExhH1YVINSq5gqGfRMTJopgrn51RgqzCVdZmVa/6mHk9dxuGQrli+kLCV6Gbro9+9dIQ0=,iv:0Ma6e0CPW9k9YBsC8QY8AirpLH2Ll9khwn1XOCA1FWo=,tag:T/cYn7cOmoTbvpV3LBROow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
