---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: blocky
      version: 10.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/0xerr0r/blocky
      tag: v0.18
    controller:
      enabled: true
      replicas: 0
      strategy: RollingUpdate
    env:
      TZ: "Europe/Amsterdam"
    service:
      main:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky
          metallb.universe.tf/loadBalancerIPs: "192.168.1.222"
        externalTrafficPolicy: Local
        ports:
          http:
            enabled: true
            port: 4000
            protocol: HTTP
      dns:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky
          metallb.universe.tf/loadBalancerIPs: "192.168.1.222"
        externalTrafficPolicy: Local
        ports:
          tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
          udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
    podAnnotations:
      configmap.reloader.stakater.com/reload: "blocky-config"
    config: |
      upstream:
        default:
          - tcp-tls:one.one.one.one:853
          # - tcp-tls:dns.quad9.net:853
      conditional:
        mapping:
          ${SECRET_DOMAIN}: tcp+udp:192.168.1.1
      customDNS:
        mapping:
          k8s.${SECRET_DOMAIN}: 10.10.5.5
      clientLookup:
        upstream: tcp+udp:192.168.1.1
      bootstrapDns: tcp+udp:1.1.1.1
      blocking:
        blackLists:
          ads:
            - https://raw.githubusercontent.com/ookangzheng/dbl-oisd-nl/master/dbl.txt
          fakenews:
            - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts
        whiteLists:
          ads:
            - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
            - |
              investing.com
        clientGroupsBlock:
          default:
            - ads
            - fakenews
      prometheus:
        enable: true
        path: /metrics
      httpPort: 4000
      logLevel: info
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 60
      failureThreshold: 2
