kind: Secret
ansible_user: ENC[AES256_GCM,data:9SyMDLK9,iv:AlAR3wGa97yU0A4u0XZvLqKbvuUjT9SCYVhV6Xn5+RY=,tag:SovglYyLzj+EnhNNlUH+Yg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Cw==,iv:nRRrlMf089xiqlOlNgFRKEkG4SjQ8j7/nW9+cDAco4E=,tag:SAloStj448FSsXda2Um9QQ==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e7eh6y2mka5euucx9xqdt70l3mcdp7dcfq5s2v7d8ahr29ww042sqfnvrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORTlNSXJmeU1ENHpVL2sw
            enVqQ0J5d1VEcVhXbmFJWDVZQnJtWHZ3amwwCjZTSGhiWWU0Q1g4eHRsZW1XRnV5
            M0VPcHNPM0JXNFhWZDJxV3l3UXlzNkEKLS0tIDYwMDZHUSs4Y2ZlaHhLOC9BY3hT
            bVZPRE9yeklReU1hNk9IaXlUYnNtTUkKAE/m3iSJNtiYrAuuhc1A6BZuT31AvseJ
            b13jk5XZgH+DfbnBcHqb8OrgTU0bQI3F9RGxLvFRWSwhK1ZRvDjHpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-29T07:53:22Z"
    mac: ENC[AES256_GCM,data:pOO+h4VyVq7+/tgQ12rI4iq+ZmSo7OcPvEsqI0P9+VVQaiitOqknL6BQeL+aXwL0UJParv8/nYWCWxs1A0oMy+6LSnzmR8gKku7ApgOuLzoKJZ6FoGFIAt5mt3B5u/gw/lqxKhib9WDFGHPHxaiRb/5oe1KASB/Dur/oM3/HAio=,iv:QDH3mkqr7/6TlhmTSQ/h5CvUiXd7xEbGMrnKv2CWYyA=,tag:WGhNI/upAHE3g1nL+AdOdg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
