kind: Secret
ansible_user: ENC[AES256_GCM,data:f2SLhTuJ,iv:zGigHAY3YHYwYynrN+8ZGMQMic3erMAHM6OsAhM5BNY=,tag:+pMyjtCt5l4F3zuzN3drSQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Pw==,iv:VGqPLH7sjEbNLPIzuGkQjRvlRQ+itDGrTDV37HyApm4=,tag:eZR/D0yq9AFh5608XHs8qw==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e7eh6y2mka5euucx9xqdt70l3mcdp7dcfq5s2v7d8ahr29ww042sqfnvrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSk5HeEFpcEtCdmQ0TWwr
            cEJteVFQcXRCMTVnRzVtQm41QWxHNndRL0hBCkswTHVXbEMwWThQRk93b3ErRlpI
            dDFFSUVMaVpCMktEbVd3emJWRTh5YUUKLS0tIEpDYWdCZkxscSthT0dmZ3U3Tzl3
            S1NZbnBVcmVFTkl0MlZ2V2s2Qzk5Y28KOj9adjMctZ4IOlGRO+JE4wczB6a8RiKM
            Hf7dRO/6jJilCkZcGBH/iB5lyQTkIuGHxAiWIctKjwV4NSxhc4bvjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-29T07:53:22Z"
    mac: ENC[AES256_GCM,data:fVM7z+GJ7QEQhQJebSOuaS0SKjK6RCLcscKfZcUzrClVhkeDY7Z6IhKMBWRAAKDHWOnfF1G8TBrHKUjWxcD4GQ96MpLAeL1DJnVKfqiCIYCtv+rHgmvjo9Lb4qUcv7PPurhTeL6tRADsv/V8GFWiGMU8RoVhuz1w9S4ZeHcLg7g=,iv:nVx2HAFL7akztyvQGighnm+EHZq4BWKbDHbO37iyd0s=,tag:JDV8mpQvZjVeTr+bcEOYtQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
