# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Q3KHkUEYdafFn7r+3DVS,iv:eIBy7Kw7MRiJ33DmgWOtzL149rI2kEVAxgsMhe/WUVI=,tag:ImsTWoktjYmn+j4plmg6hQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:yuKfuUjUFUF8x3aE6oU5T7zA,iv:ctP0ZenOoSNvwNMOMvnis/jtp1W5R6xaoFh1YoR1RMc=,tag:euyaNEPv1r2a/1MG8udpFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e7eh6y2mka5euucx9xqdt70l3mcdp7dcfq5s2v7d8ahr29ww042sqfnvrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUnByeFFwSHdITHZrOE9Z
            Vnk2SDI2N093ZWl6Q2NSMEFiM0IydGthK1JRCjlKQ0YyMnN6ZUhaWWdrNFNEQ1Uw
            ZVYySWlLZWY5Z29lSnhqbThtaWxidGcKLS0tIFpoUEZDbElNWHFhcDMrdXR0Z0hP
            elQrR2FlQmJlRmVBWG9CbVRXUS9UVkkK0Q+NAQP7fVgUTaLrTPvEfNzzOYvPSHC8
            moFVfwESlVLhVn4Z4yfKvbigA6g1L5wTRdbW7Y/5Es10WDG8muVFJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-29T07:53:22Z"
    mac: ENC[AES256_GCM,data:ecTi5uW3bQ9BZF+FwZz3mt7rMABoFbaotEq162z523ePUohlmoOeTfhaeRgpSYSK4xlY3VSSkNphzo/yZN392eNrBwdHNjSpbpZ1kimC+kh4BqYPamqgRSwqg7nriwUSY4wU4gSHBriyp2yMkZr5gNT4COu/Zega4pshPA8ipWU=,iv:pIAOkrTAqIt/5qqanC1fnUoDz1HZ7DsTKPq2NKUd/yQ=,tag:wKl0vLAQH5tCK8t7JLYwVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
