---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-plex
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-plex
      version: 0.3.1
      sourceRef:
        kind: HelmRepository
        name: kube-plex
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    claimtoken: "claim-Vi-xPb5ke9hTo-AYx7Lv"
    timezone: Europe/Amsterdam
    ingress:
      enabled: false
    persistence:
      config:
        accessMode: ReadWriteOnce
      transcode:
        storageClass: "nfs-client"
        size: 100Gi
      data:
        storageClass: "nfs-client"
        size: 10000Gi
    service:
      type: LoadBalancer
      port: 32400
      nodePort: 32400
      LoadbalancerIP: 192.168.1.224
